### ISSUE TITLE
404 on Schedule links for the web app

### ISSUE THREAD

**Issue by jeremywight** [codeforgreenville/trolley-tracker-web#11]
@dacohenii @Linktheoriginal The links on the web app take you to a blank page. Looks like that js is missing on the http://linktheorigi.webfactional.com/ site. EX Broken URL: http://linktheorigi.webfactional.com/trolley/schedule/4/

**Comment by Linktheoriginal** [comment]
Sorry for that - I modified how static files were hosted in the main view but forgot to double-check the schedule view after I deployed.  I've corrected the file reference for that view and everything looks to be working again.

**Comment by jeremywight** [comment]
Looks good! Thanks sir!
